DEBUG 2019-04-28 14:55:52,211: 	 Executing command: 'submit'
DEBUG 2019-04-28 14:55:52,211: 	 Found CRAB cache file /home/pku/anying/.crab3
DEBUG 2019-04-28 14:55:52,228: 	 Checking credentials
DEBUG 2019-04-28 14:55:52,228: 	 Proxy file /tmp/x509up_u11749 not found
DEBUG 2019-04-28 14:55:52,228: 	 Creating new proxy for 24:00 hours with VO group '' and VO role 'NULL'.
DEBUG 2019-04-28 14:55:52,831: 	 Executing : 
 command : voms-proxy-init -voms cms:/cms -valid 24:00 -rfc
 output : None
 error: None
 retcode : 1
DEBUG 2019-04-28 14:55:53,234: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u11749 -timeleft
 output : 
 error: Proxy not found: /tmp/x509up_u11749 (No such file or directory)

 retcode : 1
ERROR 2019-04-28 14:55:53,234: 	 Error while checking proxy timeleft for /tmp/x509up_u11749
DEBUG 2019-04-28 14:55:53,637: 	 Executing : 
 command : env X509_USER_PROXY=/tmp/x509up_u11749 voms-proxy-info -fqan
 output : 
 error: Proxy not found: /tmp/x509up_u11749 (No such file or directory)

 retcode : 1
ERROR 2019-04-28 14:55:53,638: 	 Problems creating proxy.
ERROR 2019-04-28 14:55:53,638: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 305, in __init__
    self.proxyCreated = self.proxy.createNewVomsProxySimple(timeLeftThreshold = 720)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/CredentialInteractions.py", line 126, in createNewVomsProxySimple
    raise ProxyCreationException("Problems creating proxy.")
ProxyCreationException: Problems creating proxy.
DEBUG 2019-04-28 15:04:13,189: 	 Executing command: 'submit'
DEBUG 2019-04-28 15:04:13,189: 	 Found CRAB cache file /home/pku/anying/.crab3
DEBUG 2019-04-28 15:04:13,194: 	 Checking credentials
DEBUG 2019-04-28 15:04:13,194: 	 Found proxy file /tmp/x509up_u11749
DEBUG 2019-04-28 15:04:13,194: 	 Getting proxy life time left
DEBUG 2019-04-28 15:04:13,697: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u11749 -timeleft
 output : 42819

 error: 
 retcode : 0
DEBUG 2019-04-28 15:04:14,200: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u11749 -actimeleft
 output : 42818

 error: 
 retcode : 0
DEBUG 2019-04-28 15:04:14,201: 	 Proxy lifetime 42819 secs is different from voms extension lifetime 42818 secs for proxy: /tmp/x509up_u11749
DEBUG 2019-04-28 15:04:14,201: 	 Proxy valid for 11:53:38 hours
INFO 2019-04-28 15:04:14,201: 	 Will use CRAB configuration file crab3_analysisZA.py
DEBUG 2019-04-28 15:04:14,201: 	 Loading CRAB configuration file.
DEBUG 2019-04-28 15:04:14,202: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-04-28 15:04:14,203: 	 Working area '/data/pku/home/anying/cms/RunII2017/CMSSW_9_4_9_cand2/src/VAJets/PKUTreeMaker/test/crab_Z-ZA-1' already exists 
Please change the requestName in the config file
ERROR 2019-04-28 15:04:14,203: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 404, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/data/pku/home/anying/cms/RunII2017/CMSSW_9_4_9_cand2/src/VAJets/PKUTreeMaker/test/crab_Z-ZA-1' already exists 
Please change the requestName in the config file
DEBUG 2019-04-28 15:20:57,327: 	 Executing command: 'status'
DEBUG 2019-04-28 15:20:57,327: 	 Found CRAB cache file /home/pku/anying/.crab3
ERROR 2019-04-28 15:20:57,328: 	 Error: crab_Z-ZA- is not a valid CRAB project directory.
ERROR 2019-04-28 15:20:57,328: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 40, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 268, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 586, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_Z-ZA- is not a valid CRAB project directory.
